title: Voeg grote teksttegels toe
hero_image: images/banner.png
description: Voeg tegels met dezelfde hoogte en breedte toe die grote tekst bevatten.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Voeg grote teksttegels toe
