title: Add large text tiles 
hero_image: images/banner.png
description: Add tiles of the same height and width that contain large text. 
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Add large text tiles 
