---
title: Ajouter des tuiles de texte de grande taille
hero_image: images/banner.png
description: Ajoute des tuiles de même hauteur et largeur contenant du texte de grande taille.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Ajouter des tuiles de texte de grande taille
